### ISSUE TITLE
Crash using IDA 7.0, Anaconda - python 2.7.13, with ipykernel 4.6.1 and ipython-qtconsole 3.2.1

### ISSUE THREAD

**Issue by dummys** [eset/ipyida#9] opened 2017-10-02 09:11 UTC
Hello,

I got a "Microsoft Visual C++ Runtime Library Error" when trying to use the ipyida plugin.
The error is R6034 the application has made an attempt to load the C runtime Library incorrectly.
Other python plugins are working correctly. Windows 7x64

**Comment by dummys** [comment] 2017-11-22 13:31
Hi, nobody look this repository anymore ?

**Comment by marc-etienne** [comment] 2017-11-23 04:23
Yes, sorry, I didn't have time to reproduce the environment (yet). Please remind me in a week here if I still haven't look at this.

**Comment by dummys** [comment] 2017-11-23 17:13
ok. no problem. Under linux, I get strange bug, when closing and reopening the jupyter console, IDA crash.
Did you have the same problem?

**Comment by DoomMuffins** [comment] 2017-12-14 11:15
Observed the same issue with Windows 10 / Miniconda2 4.3 / Python 2.7.14 / ipykernel 4.7.0 / qtconsole 4.3.1.
It seems to be distinctly related to qtconsole load, because when I don't have qtconsole installed I just get an `ImportError` for `qtconsole.qt_loaders` and when I install qtconsole the MessageBox starts appearing every launch. A quick search for similar issues points to `msvcr90.dll` and manifests: https://github.com/ivanov/vim-ipython/issues/20

**Comment by marc-etienne** [comment] 2018-01-03 19:46
I'm having a hard time reproducing your issue on Windows.

I just did a fresh install using `install_from_ida.py` on the following:

- IDA 7.0 Windows x64
- Windows 10 (1709) 64-bit
- Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]

```
> c:\Python27-64\python.exe -mpip list
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
certifi (2017.11.5)
colorama (0.3.9)
decorator (4.1.2)
enum34 (1.1.6)
ipyida (1.1)
ipykernel (4.7.0)
ipython (5.5.0)
ipython-genutils (0.2.0)
jupyter-client (5.2.1)
jupyter-core (4.4.0)
pathlib2 (2.3.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
Pygments (2.2.0)
python-dateutil (2.6.1)
pyzmq (16.0.3)
qtconsole (4.3.1)
scandir (1.6)
setuptools (38.2.5)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
tornado (4.5.2)
traitlets (4.3.2)
wcwidth (0.1.7)
win-unicode-console (0.5)

(In IDA)
> sys.path
['',
 'C:\\WINDOWS\\SYSTEM32\\python27.zip',
 'C:\\Python27-64\\Lib',
 'C:\\Python27-64\\DLLs',
 'C:\\Python27-64\\Lib\\lib-tk',
 'C:\\Program Files\\IDA 7.0\\python',
 'C:\\Python27-64',
 'C:\\Python27-64\\lib\\site-packages',
 'C:\\Program Files\\IDA 7.0\\python\\lib\\python2.7\\lib-dynload\\ida_64',
 'C:\\Program Files\\IDA 7.0\\python',
 'C:\\Users\\Marc-Etienne\\AppData\\Roaming\\Hex-Rays\\IDA Pro',
 'C:\\Python27-64\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Marc-Etienne\\.ipython',
 'C:/Program Files/IDA 7.0/loaders',
 'C:/Python27-64/lib/site-packages/ipyida']
```

How exactly did you install it? Did you use the `install_from_ida.py` script?

**Comment by DoomMuffins** [comment] 2018-01-03 20:17
Yes, I tried that too. Perhaps this is somehow specific to Anaconda/Miniconda?

**Comment by marc-etienne** [comment] 2018-01-03 21:53
Both the installation and plugin (with qtconsole and completion) works with Miniconda2.

```
> set
[...]
PYTHONHOME=C:\Users\Marc-Etienne\Miniconda2

> python -mconda info
Current conda install:

               platform : win-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\Users\Marc-Etienne\Miniconda2  (writable)
    default environment : C:\Users\Marc-Etienne\Miniconda2
       envs directories : C:\Users\Marc-Etienne\Miniconda2\envs
                          C:\Users\Marc-Etienne\AppData\Local\conda\conda\envs
                          C:\Users\Marc-Etienne\.conda\envs
          package cache : C:\Users\Marc-Etienne\Miniconda2\pkgs
                          C:\Users\Marc-Etienne\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False

> python -mpip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.23.0)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
colorama (0.3.9)
conda (4.3.31)
cryptography (2.1.4)
decorator (4.1.2)
enum34 (1.1.6)
idna (2.6)
ipaddress (1.0.18)
ipyida (1.1)
ipykernel (4.7.0)
ipython (5.5.0)
ipython-genutils (0.2.0)
jupyter-client (5.2.1)
jupyter-core (4.4.0)
menuinst (1.4.10)
pathlib2 (2.3.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
pycosat (0.6.3)
pycparser (2.18)
Pygments (2.2.0)
pyOpenSSL (17.5.0)
PySocks (1.6.7)
python-dateutil (2.6.1)
pywin32 (221)
pyzmq (16.0.3)
qtconsole (4.3.1)
requests (2.18.4)
ruamel-yaml (0.11.14)
scandir (1.6)
setuptools (38.2.5)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
tornado (4.5.2)
traitlets (4.3.2)
urllib3 (1.22)
wcwidth (0.1.7)
wheel (0.30.0)
win-inet-pton (1.0.1)
win-unicode-console (0.5)
wincertstore (0.2)

IDA> sys.path
['',
 'C:\\WINDOWS\\SYSTEM32\\python27.zip',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\DLLs',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\plat-win',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\lib-tk',
 'c:\\Program Files\\IDA 7.0',
 'c:\\Program Files\\IDA 7.0\\python',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\site-packages',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\site-packages\\win32',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\site-packages\\Pythonwin',
 'c:\\Program Files\\IDA 7.0\\python\\lib\\python2.7\\lib-dynload\\ida_64',
 'c:\\Program Files\\IDA 7.0\\python',
 'C:\\Users\\Marc-Etienne\\AppData\\Roaming\\Hex-Rays\\IDA Pro',
 'C:\\Users\\Marc-Etienne\\Miniconda2\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Marc-Etienne\\.ipython',
 'c:/Program Files/IDA 7.0/loaders',
 'C:/Users/Marc-Etienne/Miniconda2/lib/site-packages/ipyida']
```

I will need more details to debug this further because I'm unable to reproduce. Does it say which DLL is unable to load? What does you `sys.path` look like? Are you sure it's using the qt bindings from IDA?

**Comment by DoomMuffins** [comment] 2018-01-04 22:26
Note the difference in the location of python27.zip:
```
Python>pprint(sys.path)
['',
 'C:\\ProgramData\\Miniconda2\\python27.zip',
 'C:\\ProgramData\\Miniconda2\\Lib',
 'C:\\ProgramData\\Miniconda2\\DLLs',
 'C:\\Program Files\\IDA 7.0',
 'C:\\Program Files\\IDA 7.0\\python',
 'C:\\ProgramData\\Miniconda2',
 'C:\\ProgramData\\Miniconda2\\lib\\site-packages',
 'C:\\ProgramData\\Miniconda2\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Miniconda2\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Miniconda2\\lib\\site-packages\\Pythonwin',
 'C:\\Program Files\\IDA 7.0\\python\\lib\\python2.7\\lib-dynload\\ida_32',
 'C:\\Program Files\\IDA 7.0\\python',
 'C:\\Users\\<User>\\AppData\\Roaming\\Hex-Rays\\IDA Pro',
 'C:\\ProgramData\\Miniconda2\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\<User>\\.ipython']
```
I tried the following:
* Uninstalling qtconsole, causing ipyida to fail loading
* Running IDA
* Installing qtconsole
* Running `import ipyida.ida_plugin`
The messagebox then pops.
In procmon, I see the following:
![image](https://user-images.githubusercontent.com/2357203/34586991-0f68d578-f1af-11e7-9041-c4b5e3dda3c4.png)

**Comment by marc-etienne** [comment] 2018-01-09 20:23
I was finally able to replicate by uninstalling all Python and Miniconda installs and running IDA from the Anaconda shell (yay!).

The "crash" is produced while loading qtconsole's widget: https://github.com/jupyter/qtconsole/blob/4.2.1/qtconsole/rich_jupyter_widget.py#L18

Which loads IPython:
https://github.com/ipython/ipython/blob/5.5.0/IPython/lib/latextools.py#L13

Which eventually loads `pywintypes`. `mscvr90.dll` is listed in `pywintypes.dll` dependencies, but tries to load it from because Mini/Anaconda prepends to the `PATH` envvar `C:\ProgramData\Miniconda2;[...]`. Perhaps Miniconda needs to add a manifest to `pywintypes.dll`, I'm no expert in Windows dependencies for software distribution.

What I experience is not a crash, just a message but then IPyIDA works fine.

I solved it by removing `C:\ProgramData\Miniconda2` from `os.environ['path']` before loading `ipyida`. You can do it in your `idapythonrc.py` file.

See: https://stackoverflow.com/questions/14552348/runtime-error-r6034-in-embedded-python-application

**Comment by DoomMuffins** [comment] 2018-01-10 22:04
I investigated further; It seems that `python27.dll` has a manifest describing a dependency on the assembly `Microsoft.VC90.CRT`, which causes `msvcr90.dll` to be loaded from the side-by-side assembly cache (`WinSxS`). When `python27.dll` is loaded, its `DllMain / DLL_PROCESS_ATTACH` saves the activation context derived from its own manifest in a global variable. Every time `python27.dll` is requested to load a native C module (mostly `.pyd`, some `.dll`), [the saved activation context is applied](https://github.com/python/cpython/blob/0ebf0ae6a2b055f6a2373d9d1976f6b243ed8b00/Python/dynload_win.c#L193) for the duration of the `LoadLibraryEx` call. This means that native C modules that have no manifest are loaded in the activation context of `python27.dll`, derived from its manifest. 

There are some peculiarities in `pywin32`, however; `pywintypes.py` [calls into a native module](https://github.com/mhammond/pywin32/blob/7da19cd2ca3fac06638d9af690b8b6f5fcc65e8b/win32/Lib/pywintypes.py#L79) called `_win32sysloader` for some hidden `LoadLibrary` shenanigans (see [here](https://github.com/mhammond/pywin32/blob/375dca3f9e3da08ba4c4a89149c71eb61b72ee4f/win32/src/_win32sysloader.cpp#L59)). This bypasses `python27.dll`'s activation context management, causing a native library (`pythoncom`, see [here](https://github.com/mhammond/pywin32/blob/7da19cd2ca3fac06638d9af690b8b6f5fcc65e8b/com/pythoncom.py#L3)) which is actually a python C module to be loaded with `ida.exe`'s ambient activation context, which holds no entry for `msvcr90.dll`. This causes a search through the library search paths and the problem we see above. 

For now, I replaced the line in `pywintypes.py` from
``` found = _win32sysloader.LoadModule(filename) ```
to
```__import__(modname, globs)```
This workaround seems to work; The message box doesn't pop up anymore. Another workaround could be copying the relevant manifest line from `python27.dll`'s manifest to `ida.exe`'s manifest.  I'm not sure what the correct fix is design-wise, but it's clearly either in `CPython` or in `pywin32` (or both).

**Comment by marc-etienne** [comment] 2018-01-12 16:05
Looks like you dug even further :), but yeah everything you found make sense.

Bottom line, the issue is not specific to IPyIDA, but with Conda <-> pywin32 <-> IDA so I'm closing this issue here. If someone else runs into this issue there should be enough details here to help them debug/fix.

Thanks!

**Closed by marc-etienne** 2018-01-12 16:05 UTC
